version: 2.1

jobs:

  test:
    docker:
      - image: rust:slim
    steps:
      - checkout
      - restore_cache:
          keys:
            - test-registry-v1-{{ .Branch }}-{{ .Revision }}
            - test-registry-v1-{{ .Branch }}-
            - test-registry-v1-
      - run:
          name: Check formatting
          command: |
            rustup component add rustfmt
            rustfmt --check **/*.rs
      - run:
          name: Linting
          command: |
            rustup component add clippy
            cargo clippy --all-features -- -D warnings
      - save_cache:
          key: test-registry-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - /root/.cargo/registry
            - /root/.cargo/bin/rustfmt
            - /root/.cargo/bin/clippy
            - ./target

  benchmark:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - restore_cache:
          keys:
            - benchmark-registry-v1-{{ .Branch }}-{{ .Revision }}
            - benchmark-registry-v1-{{ .Branch }}-
            - benchmark-registry-v1-
      - run:
          name: Run benchmark
          command: |
            (
              echo '### Benchmark Results'
              echo
              echo 'After:'
              echo '```none'
              cargo bench | grep bench:
              echo '```'
              git reset --hard origin/master > /dev/null
              echo
              echo 'Before:'
              echo '```none'
              cargo bench | grep bench:
              echo '```'
            ) > /tmp/comment
            curl -sSL https://gist.githubusercontent.com/cecton/538ce1a6e0b645bd6cbbecf6ccf51366/raw/de93dfdf7182c07eebbfa258ca5a38a0c8149e01/circleci_comment_on_github.sh | sh -
      - save_cache:
          key: benchmark-registry-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - /root/.cargo/registry
            - ./target

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - benchmark:
          filters:
            branches:
              ignore: master
